/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package OneHarborAppUI;

import java.io.File;
import java.io.IOException;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;
import one.harbor.app.CSVUtilities;

/**
 *
 * @author eimi_
 */
public class OneHarborAppUI extends javax.swing.JFrame {
    
    /**
     * Creates new form OneHarborAppUI
     */
    public OneHarborAppUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        StartButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        CustomReportFileTextBox = new javax.swing.JTextField();
        DeptSummaryFileTextBox = new javax.swing.JTextField();
        OFD_CustomReportButton = new javax.swing.JButton();
        OFD_DeptSummaryButton = new javax.swing.JButton();
        ToggleOversightCSVButton = new javax.swing.JToggleButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("One Harbor App");

        StartButton.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        StartButton.setText("Start");
        StartButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                StartButtonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel1.setText("Custom Report file:");

        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setText("Dept. Summary  file:");

        CustomReportFileTextBox.setText("custom_report.csv");
        CustomReportFileTextBox.setEnabled(false);

        DeptSummaryFileTextBox.setText("department_summary.csv");
        DeptSummaryFileTextBox.setEnabled(false);

        OFD_CustomReportButton.setText("...");
        OFD_CustomReportButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OFD_CustomReportButtonActionPerformed(evt);
            }
        });

        OFD_DeptSummaryButton.setText("...");
        OFD_DeptSummaryButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OFD_DeptSummaryButtonActionPerformed(evt);
            }
        });

        ToggleOversightCSVButton.setText("Create Oversight Pastor CSVs: Off");
        ToggleOversightCSVButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ToggleOversightCSVButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(CustomReportFileTextBox)
                            .addComponent(DeptSummaryFileTextBox))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(OFD_CustomReportButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(OFD_DeptSummaryButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ToggleOversightCSVButton))
                        .addGap(0, 436, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(3, 3, 3)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CustomReportFileTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OFD_CustomReportButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DeptSummaryFileTextBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(OFD_DeptSummaryButton, javax.swing.GroupLayout.PREFERRED_SIZE, 26, Short.MAX_VALUE))
                .addGap(16, 16, 16)
                .addComponent(ToggleOversightCSVButton)
                .addGap(18, 18, 18)
                .addComponent(StartButton, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void StartButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_StartButtonActionPerformed
        
        Boolean makeOversightCSVs = ToggleOversightCSVButton.isSelected();
        File ifExists = new File(CustomReportFileTextBox.getText());
        if(ifExists.exists() && !ifExists.isDirectory()){
            ifExists = new File(DeptSummaryFileTextBox.getText());
            if(ifExists.exists() && !ifExists.isDirectory()){
                try {            
                    // TODO add your handling code here:
                    CSVUtilities.CreateMemberInfo(CustomReportFileTextBox.getText(), DeptSummaryFileTextBox.getText());
                } catch (IOException ex) {
                    Logger.getLogger(OneHarborAppUI.class.getName()).log(Level.SEVERE, null, ex);
                }
                try {
                    CSVUtilities.WorkWithOHPSDatabase(CustomReportFileTextBox.getText(), DeptSummaryFileTextBox.getText(), makeOversightCSVs);
                } catch (SQLException ex) {
                    Logger.getLogger(OneHarborAppUI.class.getName()).log(Level.SEVERE, null, ex);
                } catch (IOException ex) {
                    Logger.getLogger(OneHarborAppUI.class.getName()).log(Level.SEVERE, null, ex);
                }        
                MessageBox.InfoBox("Completed File Creation.", "Done");
            }
            else{
                MessageBox.ErrorBox("Dept. Summary file doesn't exist.", "No Dept. Summary CSV");
            }            
        }
        else{
            MessageBox.ErrorBox("Custom Report file doesn't exist.", "No Custom Report CSV");
        }
    }//GEN-LAST:event_StartButtonActionPerformed

    private void OFD_CustomReportButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OFD_CustomReportButtonActionPerformed
        try {
            // TODO add your handling code here:
            CustomReportFileTextBox.setText(SetPath());
        } catch (IOException ex) {
            Logger.getLogger(OneHarborAppUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_OFD_CustomReportButtonActionPerformed

    private void OFD_DeptSummaryButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OFD_DeptSummaryButtonActionPerformed
        // TODO add your handling code here:
        try {
            // TODO add your handling code here:
            DeptSummaryFileTextBox.setText(SetPath());
        } catch (IOException ex) {
            Logger.getLogger(OneHarborAppUI.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_OFD_DeptSummaryButtonActionPerformed

    private void ToggleOversightCSVButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ToggleOversightCSVButtonActionPerformed
        // TODO add your handling code here:
        if(ToggleOversightCSVButton.isSelected()){ToggleOversightCSVButton.setText("Create Oversight Pastor CSVs: On");}else{ToggleOversightCSVButton.setText("Create Oversight Pastor CSVs: Off");}
    }//GEN-LAST:event_ToggleOversightCSVButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(OneHarborAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(OneHarborAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(OneHarborAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(OneHarborAppUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new OneHarborAppUI().setVisible(true);
            }
        });
    }
    
    private String SetPath() throws IOException{
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setMultiSelectionEnabled(false);
        fileChooser.setFileSelectionMode(JFileChooser.FILES_ONLY);
        File file = null;

        FileFilter filter = new FileFilter() {

            @Override
            public String getDescription() {
                return "CSV Files | (*.csv)";
            }

            @Override
            public boolean accept(File f) {
                return f.getName().contains(".csv")
                        || f.isDirectory();
            }
        };
        fileChooser.addChoosableFileFilter(filter);
        fileChooser.setFileFilter(filter);
        fileChooser.setAcceptAllFileFilterUsed(false);

        int retunval = fileChooser.showOpenDialog(OneHarborAppUI.this);
        if (retunval == JFileChooser.APPROVE_OPTION) {
            try {
                file = fileChooser.getSelectedFile();
                return file.getCanonicalPath();
            } catch (IOException e) {
                // TODO Auto-generated catch block                
                e.printStackTrace();
                MessageBox.ErrorBox("Error in JFileChooser.", "Error", e);
                return null;
            }finally{
                return file.getCanonicalPath();
            }
        }
        return file.getCanonicalPath();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CustomReportFileTextBox;
    private javax.swing.JTextField DeptSummaryFileTextBox;
    private javax.swing.JButton OFD_CustomReportButton;
    private javax.swing.JButton OFD_DeptSummaryButton;
    private javax.swing.JButton StartButton;
    private javax.swing.JToggleButton ToggleOversightCSVButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
}
